name: ldcpy_dev
channels:
  - conda-forge
dependencies:
  - cartopy=0.18
  - netcdf4
  - pip
  - xarray
  - zfpy
  - xrft
  - cmocean
  - numpy
  - scipy
  - matplotlib-base
  - pre-commit
  - setuptools
  - jupyterlab
  - jupyter_contrib_nbextensions
  - graphviz
  - codecov
  - pytest
  - pytest-cov
  - pytest-xdist
  - dask
  - intake-esm
  - nc-time-axis
  - pandas
  - cython
  - scikit-image
  - opencv=4.2.0
